language: java
jdk:
  - openjdk11
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw heroku:deploy jib:build -P deploy-heroku

after_success:
  - bash <(curl -s https://codecov.io/bash -t df7cc247-5b4e-47e0-b6da-4fd1bc8f0875)
